### ISSUE TITLE
[Suggestion] [Ubuntu] getting the codename with a command shortens the script

### ISSUE THREAD

**Issue by GeorgScheumann** [Klairm/Linux-Gaming-Setup#1]
Hi there,

using  `$(lsb_release -c | sed s/Codename:/''/g)` while adding the wine repository, instead of the hard coded codenames significantly shortens the script, since only one paragraph with Ubuntu is needed, I just tested it and it seems to work.

I attached my modified programs.py below, just note that I am not good at coding, which is why I left the version check variable more or less intact, so it doesn't break things.
[programs.py.txt](https://github.com/Klairm/Linux-Gaming-Setup/files/4498294/programs.py.txt)

**Comment by Klairm** [comment]
Will add this to the script, thanks for sharing!

**Comment by Klairm** [comment]
Seems like that broked it, the command will take $(lsb_release -c | sed s/Codename:/''/g) literally as text, will revert back until I fix this

**Comment by GeorgScheumann** [comment]
Oh my bad,

seems I didn't test my change properly...
Anyway try to use this instead:` sudo apt-add-repository deb\ https://dl.winehq.org/wine-builds/ubuntu/\ $(lsb_release -c | sed 's/Codename:\t/''/g')\ main`

The problem with single brackets is that everything inside them is treated as text, so I replaced them.
