### ISSUE TITLE
Error with enableMultilib.py

### ISSUE THREAD

**Issue by edwardsaunders7** [Klairm/Linux-Gaming-Setup#11]
Having a problem with the GamingSetup.py - it says 

"sudo: enableMultilib.py: command not found" - despite the file being present. 

When trying to run the python script separately using "./enableMultilib.py" it says "permission denied", when trying to run it the same way with sudo, it says "command not found.

Trying to run it using python3 says:
"File "enableMultilib.py", line 42, in <module>
pacmanConf(sys.argv[1])
IndexError: list index out of range"

Any advice? Using manjaro linux

**Comment by Klairm** [comment]
Youre trying to install drivers? I just noticed there's a typo on the code, sorry for that! Gonna update it ASAP

**Comment by edwardsaunders7** [comment]
Great! All worked now! Thanks :)
