### ISSUE TITLE
[request] Add more usefull tools

### ISSUE THREAD

**Issue by tamodolo** [Klairm/Linux-Gaming-Setup#6]
Nice script but very basic.

I have some sugestions that may be very welcome by all. I'll list what and why below:

- Install Custom Proton (like proton-GE) - This increase compatibility
- Install Desktop focused kernel insteal server/general focused kernel (like Zen, Xanmod and Liquorix) - These kernels have alternative schedulers that will increase game performance/response and improve latency greatly.
- Install dkms driver versions - for compatibility with desktop kernels
- Install Gamemode - improves game performance
- verify esync situation - because we still have some distros that limit it

For some other somewhat specific tools that I don't have a particular app to recomend:

- install something to configure controlers (like DS4, Xbox and anything else) - The DS4 is particularly bad on linux out of the box...

**Comment by Klairm** [comment]
Thanks for the suggestion, I'll add this tools when I get some time, thanks!

**Comment by Klairm** [comment]
I already have the feral gamemode added at least on testing branch, about Proton GE, installing lastest release avaible is fine right?
About dkms driver and custom kernels, I will add those when I first test them myself for some days

**Comment by tamodolo** [comment]
About Proton-GE, yes. I do agree with the latest oficial release. Thanks for these aditions! They are very apreciated!

**Comment by Klairm** [comment]
Since everything has been added except for kernel installation and controller configuration , I will close this issue, the main problem with kernel compilation is that it requires some user input and checking, and tbh only people who know what they are doing should be installing custom kernel with their personal configurations
